# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 00:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hdsysUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf', models.PositiveIntegerField(unique=True)),
                ('rg', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('register_date', models.DateTimeField(null=True)),
                ('register_status', models.BooleanField(default=False)),
                ('psw_temp', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='hdsysEditMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_date', models.DateTimeField()),
                ('previous_measure_date', models.DateTimeField()),
                ('previous_heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_max_pressure', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_min_pressure', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_glucose', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hdsysLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='hdsysLogout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logout_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='hdsysPrivateMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insertion_date', models.DateTimeField()),
                ('measure_date', models.DateTimeField(help_text='Exemplo: 25/10/2016 21:45:00')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('max_pressure', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('min_pressure', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('glucose', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
            ],
        ),
        migrations.CreateModel(
            name='hdsysAdministrator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hdsysDeleteMeasure',
            fields=[
                ('measure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hdsysapp.hdsysPrivateMeasure')),
                ('delete_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='hdsysManager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hdsysPatient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('plan', models.CharField(choices=[('SUS', 'SUS'), ('PLAN', 'Plano'), ('PARTICULAR', 'Particular')], max_length=10)),
                ('sex', models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Feminino')], max_length=6)),
                ('ethnicity', models.CharField(choices=[('WHITE', 'Branco'), ('BROWN', 'Pardo'), ('BLACK', 'Preto'), ('YELLOW', 'Amarelo'), ('INDIGENOUS', 'Indígena')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(300.0)])),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)])),
            ],
        ),
        migrations.CreateModel(
            name='hdsysProfessional',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hdsysPublicMeasure',
            fields=[
                ('measure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hdsysapp.hdsysPrivateMeasure')),
            ],
        ),
        migrations.AddField(
            model_name='hdsysprivatemeasure',
            name='measure_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hdsyslogout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hdsyslogin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hdsyseditmeasure',
            name='edit_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hdsyseditmeasure',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdsysapp.hdsysPrivateMeasure'),
        ),
        migrations.AddField(
            model_name='hdsysprivatemeasure',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdsysapp.hdsysPatient'),
        ),
        migrations.AddField(
            model_name='hdsyspatient',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdsysapp.hdsysProfessional'),
        ),
        migrations.AddField(
            model_name='hdsysdeletemeasure',
            name='delete_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
